services:
  - type: web
    name: mod-delivery
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: BASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
